#!/bin/bash
set -e
#
if [ `id -u` != 0 ];then
        echo Permission delay, Please run as root!
        exit
fi

if [ -n $JOBS ];then
        JOBS=`grep -c ^processor /proc/cpuinfo 2>/dev/null`
        if [ ! $JOBS ];then
                JOBS="1"
        fi
fi
export MAKEFLAGS=-j$JOBS

PKG_PATH=unit
BLFS_SRC_DIR=/sources/blfs-sources

usage()
{
	echo "Usage: $0 [option] [args]"
	echo "        不带参数:安装所有软件包"
	echo "	-d ,--download:下载软件包"
	echo "	-i ,--install:安装单个软件包"
}

install-pkg()
{
#检测pkg必要文件
#if [ ! -e $PKG_PATH/$1.info ];then
#	echo Not exist $1.info
#	exit
#fi

if [ ! -e $PKG_PATH/$1.cmd ];then
	echo Not exist $PKG_PATH/$1.cmd
	exit
fi

#安装有依赖的软件包
if [ -e $PKG_PATH/$1.dep ];then
	depend_pkg=`cat $PKG_PATH/$1.dep`
	install-pkg $depend_pkg
fi

#如果已经安装过，则无需再次安装
set +e
grep $1 /haoos/LIST > /dev/null
if [ $? != 0 ];then
	set -e

	exec_cmd $1
#	echo $1.cmd

fi
set -e
}

exec_cmd()
{
set +e
#获取软件包url的第一行的压缩包名
compressed_pkg_name=`grep Download $PKG_PATH/$1.info | head -1| awk -F '/' '{print $NF}'`
pkg_dir=`echo $compressed_pkg_name | awk -F '.tar' '{print $1}' | awk -F '.tgz' '{print $1}'| awk -F '.zip' '{print $1}' | awk -F '.src' '{print $1}'`
set -e
	pushd /lfs
	rm -rf $pkg_dir
	#判断压缩包是否存在
	if [ -e $BLFS_SRC_DIR/$compressed_pkg_name ];then
	  #解压缩软件包
	  decompress $BLFS_SRC_DIR/$compressed_pkg_name
	else
	  echo "Not exist $pkg_dir, maybe you have not download it, try 'dpk-install -d' to download it." && exit
	fi
	pushd $pkg_dir

	#. ./$PKG_PATH/$1.cmd && echo $1 >> /haoos/LIST
	. /haoos/$PKG_PATH/$1.cmd && echo $1 >> /haoos/LIST

	popd #$pkg_dir
	rm -rf $pkg_dir
	popd #/lfs
}

decompress()
{
	file_type=`file -b $1 | awk -F ' ' '{print$1}'`
	if [ $file_type = gzip ];then
		tar xf $1 -C /lfs
	elif [ $file_type = XZ ];then
		tar xf $1 -C /lfs
	elif [ $file_type = bzip2 ];then
		tar xf $1 -C /lfs
	elif [ $file_type = Zip ];then
		if [ $1 = /sources/blfs-sources/docbook-xml-4.5.zip ];then
		  mkdir /lfs/docbook-xml-4.5
		  unzip -d /lfs/docbook-xml-4.5 $1
		else
		  unzip -d /lfs $1
		fi
	else
		echo "unknown compressed file $1, type is: $file_type." && exit
	fi

		

}

#入参检测
#如果没有后缀参数，则安装所有包
if [ -z $1 ];then
  for pkg in `find unit/ -name *.cmd -type f`
  do
	#获取包名
	name=`echo $pkg | awk -F '[./]+' '{print $2}'`
	install-pkg $name
  done
  echo "已完成所有软件包安装" && exit
fi

if [[ ! -z $1 ]] && [[ ! -z $2 ]];then
	case $1 in
	-d )
		# --download,下载软件包
		for pkg_url in `cat $PKG_PATH/$2.info | awk -F ' ' '{print $2}'`
		do
		  wget -P /sources/blfs-sources --no-check-certificate -c $pkg_url
	  	done
	;;
	-i)
		# --install,安装单个软件包
		#rm /haoos/LIST
		touch /haoos/LIST
		install-pkg $2
	;;
	*)
		usage
	;;
	esac
else
		usage
fi
